=== aleksasiriski/xml/licnakarta.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:complexType name="datum">
    <xs:sequence>
    	<xs:element name="datum" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="format" type="xs:string" use="required"/>
</xs:complexType>

<xs:simpleType name="pol">
	<xs:restriction base="xs:string">
		<xs:minLength value="1"/>
		<xs:maxLength value="1"/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="prebivaliste">
    <xs:sequence>
    	<xs:element name="mesto" type="xs:string"/>
    	<xs:element name="adresa" type="xs:string"/>
    	<xs:element name="broj" type="xs:positiveInteger"/>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="jmbg">
	<xs:restriction base="xs:string">
		<xs:pattern value="[0-9]{13}"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="regbr">
	<xs:restriction base="xs:string">
		<xs:pattern value="[0-9]{9}"/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="osoba">
    <xs:sequence>
        <xs:element name="ime" type="xs:string"/>
        <xs:element name="prezime" type="xs:string"/>
        <xs:element name="datum" type="datum"/>
        <xs:element name="pol" type="pol"/>
        <xs:element name="prebivaliste" type="prebivaliste"/>
        <xs:element name="jmbg" type="jmbg"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="dokument">
    <xs:sequence>
        <xs:element name="regbr" type="regbr"/>
        <xs:element name="datumIzdavanja" type="datum"/>
        <xs:element name="vaziDo" type="datum"/>
        <xs:element name="dokumentIzdaje" type="xs:string"/>
    </xs:sequence>
</xs:complexType>

<xs:element name="licnakarta">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="osoba" type="osoba"/>
      <xs:element name="dokument" type="dokument"/>
      <xs:element name="osoba1" type="osoba"/>
      <xs:element name="dokument1" type="dokument"/>
      <xs:element name="osoba2" type="osoba"/>
      <xs:element name="dokument2" type="dokument"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== aleksasiriski/xml/licnakarta1.xml
<?xml version="1.0" encoding="UTF-8"?>
<licnakarta
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="licnakarta.xsd">
  <osoba>
  	<ime>Djuro</ime>
  	<prezime>Jaksic</prezime>
  	<datum format="dd.MM.yyyy."><datum>11.08.1992.</datum></datum>
  	<pol>Z</pol>
  	<prebivaliste>
  		<mesto>Novi Sad</mesto>
  		<adresa>Janka Cmelika</adresa>
  		<broj>27</broj>
  	</prebivaliste>
  	<jmbg>1234567890123</jmbg>
  </osoba>
  <dokument>
  	<regbr>123456789</regbr>
  	<datumIzdavanja format="dd.MM.yyyy."><datum>12.02.2020.</datum></datumIzdavanja>
  	<vaziDo format="dd.MM.yyyy."><datum>12.02.2025.</datum></vaziDo>
  	<dokumentIzdaje>PU u Novom Sadu</dokumentIzdaje>
  </dokument>
</licnakarta>

=== aleksasiriski/xml/licnakarta2.xml
<?xml version="1.0" encoding="UTF-8"?>
<licnakarta
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="licnakarta.xsd">
  <osoba>
  	<ime>Jelena</ime>
  	<prezime>Karleusa</prezime>
  	<datum format="dd.MM.yyyy."><datum>17.08.1978.</datum></datum>
  	<pol>M</pol>
  	<prebivaliste>
  		<mesto>Vranje</mesto>
  		<adresa>Bezimena</adresa>
  		<broj>1</broj>
  	</prebivaliste>
  	<jmbg>1234567890123</jmbg>
  </osoba>
  <dokument>
  	<regbr>123456789</regbr>
  	<datumIzdavanja format="dd.MM.yyyy."><datum>17.08.2069.</datum></datumIzdavanja>
  	<vaziDo format="dd.MM.yyyy."><datum>17.08.2074.</datum></vaziDo>
  	<dokumentIzdaje>PU u Novom Sadu</dokumentIzdaje>
  </dokument>
</licnakarta>

=== aleksasiriski/xml/licnakarta.xml
<?xml version="1.0" encoding="UTF-8"?>
<licnakarta
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="licnakarta.xsd">
  <osoba>
  	<ime>Marko</ime>
  	<prezime>98</prezime>
  	<datum format="dd.MM.yyyy."><datum>10.07.1991.</datum></datum>
  	<pol>M</pol>
  	<prebivaliste>
  		<mesto>Novi Sad</mesto>
  		<adresa>Janka Cmelika</adresa>
  		<broj>26</broj>
  	</prebivaliste>
  	<jmbg>1234567890123</jmbg>
  </osoba>
  <dokument>
  	<regbr>123456789</regbr>
  	<datumIzdavanja format="dd.MM.yyyy."><datum>11.01.2020.</datum></datumIzdavanja>
  	<vaziDo format="dd.MM.yyyy."><datum>11.01.2025.</datum></vaziDo>
  	<dokumentIzdaje>PU u Novom Sadu</dokumentIzdaje>
  </dokument>



  <osoba1>
  	<ime>Djuro</ime>
  	<prezime>Jaksic</prezime>
  	<datum format="dd.MM.yyyy."><datum>11.08.1992.</datum></datum>
  	<pol>Z</pol>
  	<prebivaliste>
  		<mesto>Novi Sad</mesto>
  		<adresa>Janka Cmelika</adresa>
  		<broj>27</broj>
  	</prebivaliste>
  	<jmbg>1234567890123</jmbg>
  </osoba1>
  <dokument1>
  	<regbr>123456789</regbr>
  	<datumIzdavanja format="dd.MM.yyyy."><datum>12.02.2020.</datum></datumIzdavanja>
  	<vaziDo format="dd.MM.yyyy."><datum>12.02.2025.</datum></vaziDo>
  	<dokumentIzdaje>PU u Novom Sadu</dokumentIzdaje>
  </dokument1>


  <osoba2>
  	<ime>Jelena</ime>
  	<prezime>Karleusa</prezime>
  	<datum format="dd.MM.yyyy."><datum>17.08.1978.</datum></datum>
  	<pol>M</pol>
  	<prebivaliste>
  		<mesto>Vranje</mesto>
  		<adresa>Bezimena</adresa>
  		<broj>1</broj>
  	</prebivaliste>
  	<jmbg>1234567890123</jmbg>
  </osoba2>
  <dokument2>
  	<regbr>123456789</regbr>
  	<datumIzdavanja format="dd.MM.yyyy."><datum>17.08.2069.</datum></datumIzdavanja>
  	<vaziDo format="dd.MM.yyyy."><datum>17.08.2074.</datum></vaziDo>
  	<dokumentIzdaje>PU u Novom Sadu</dokumentIzdaje>
  </dokument2>
</licnakarta>
